title: visuale.com.au # your name (or website title) here
logo: "/images/profile_1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  10 years+ experience as an overthinking consultant. Back in the game. Here is where and what I'm working on...
  <br><br>
  <a href="/pdf/Basil Rakawi 2024">Download My Current CV</a>
  <br><br>
  <a href="https://www.linkedin.com/in/basilrakawi/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-RCD3W6P3GR # your Google Analytics tracking ID here
