title: visuale.com.au # your name (or website title) here
logo: "/images/profile_1.png?raw=true" # your photo (or logo) here
description: >
  Over 12+ years data wrangling, storytelling & visualising in the enterprise & emerging tech space.<br/><br/>Building things that last<br/>...by breaking them in stealth.
  <br><br>
  <a href="/pdf/Basil Rakawi 2025">Download CV/Resume</a>
  <br><br>
  <a href="https://learn.microsoft.com/en-au/users/basilrakawi/credentials/certification/fabric-analytics-engineer-associate?tab=credentials-tab">Microsoft Certified</a> 
  <br>
  <a href="https://skillshop.credential.net/c417b9e4-4425-4467-8ae5-af569cdaff3b">Google Certified</a>
  <br><br>
  <a href="https://www.linkedin.com/in/basilrakawi/">My LinkedIn</a> 
  <br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-RCD3W6P3GR # your Google Analytics tracking ID here
